server:
  port: 8301
spring:
  application:
    name: borrowService
  datasource:
    password: Root1@root
    username: root
    url: jdbc:mysql://113.125.52.186:3306/cloudstudy?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka, http://localhost:8889/eureka