server:
  port: 8888
spring:
  application:
    name: eurekaServer-01
eureka:
  client:
    # 服务端角色, 不需要获取服务端
    fetch-registry: false
    # 不需要将自己注册到服务中
#    register-with-eureka: false
    # 将eureka服务器指向自己
    service-url:
#      defaultZone: http://localhost:8889/eureka
      defaultZone: http://eureka02:8889/eureka